apiVersion: v1
kind: Service
metadata:
  name: zigbee2mqtt
  labels:
    app: zigbee2mqtt
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: web
  clusterIP: None
  selector:
    app: zigbee2mqtt
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zigbee2mqtt
spec:
  selector:
    matchLabels:
      app: zigbee2mqtt
  serviceName: "zigbee2mqtt"
  replicas: 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: zigbee2mqtt
        image: koenkk/zigbee2mqtt:1.23.0
        securityContext:
          privileged: true
        ports:
        - containerPort: 8080
          name: web
        volumeMounts:
        - name: ttyacm
          mountPath: /dev/ttyACM0
        - name: z2m-config
          mountPath: /app/data
          readOnly: true
        - name: udev
          mountPath: /run/udev
          readOnly: true
      volumes:
        - name: ttyacm
          hostPath:
            path: /dev/ttyACM0
        - name: udev
          hostPath:
            path: /run/udev
        - name: z2m-config
          persistentVolumeClaim:
            claimName: nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: freenas.home.jlh.name
    path: "/mnt/solid/k8s/zigbee2mqtt"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
