apiVersion: apps/v1
kind: Pod
metadata:
  name: zigbee2mqtt
spec:
  hostNetwork: true
  containers:
  - name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.23.0
    securityContext:
      privileged: true
    volumeMounts:
    - name: ttyacm
      mountPath: /dev/ttyACM0
    - name: z2m-config
      mountPath: /app/data
    - name: udev
      mountPath: /run/udev
      readOnly: true
  volumes:
    - name: ttyacm
      hostPath:
        path: /dev/ttyACM0
    - name: udev
      hostPath:
        path: /run/udev
    - name: z2m-config
      hostPath: /mnt
