apiVersion: v1
kind: Service
metadata:
  name: zigbee2mqtt
  labels:
    app: zigbee2mqtt
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: web
  clusterIP: None
  selector:
    app: zigbee2mqtt
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zigbee2mqtt
spec:
  selector:
    matchLabels:
      app: zigbee2mqtt
  serviceName: "zigbee2mqtt"
  replicas: 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: zigbee2mqtt
        image: koenkk/zigbee2mqtt:1.23.0
        securityContext:
          privileged: true
        ports:
        - containerPort: 8080
          name: web
        volumeMounts:
        - name: ttyacm
          mountPath: /dev/ttyACM0
        - name: z2m-config
          mountPath: /app/data
          readOnly: true
        - name: udev
          mountPath: /run/udev
          readOnly: true
      volumes:
        - name: ttyacm
          hostPath:
            path: /dev/ttyACM0
        - name: z2m-config
          configMap:
            name: z2m-config
            items:
              - key: "configuration.yaml"
                path: "configuration.yaml"
        - name: udev
          hostPath:
            path: /run/udev
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: z2m-config
data:
  configuration.yaml: |
    # Home Assistant integration (MQTT discovery)
    homeassistant: true
    
    # allow new devices to join
    permit_join: true
    
    # MQTT settings
    mqtt:
      # MQTT base topic for zigbee2mqtt MQTT messages
      base_topic: zigbee2mqtt
      # MQTT server URL
      server: 'mqtt://10.1.16.3'
      # MQTT server authentication, uncomment if required:
      # user: my_user
      # password: my_password
    
    # Serial settings
    serial:
      # Location of CC2531 USB sniffer
      port: /dev/ttyACM0
